# os: linux
dist: trusty
language: node_js
node_js: "10"
sudo: required

before_install:
  - node --version
  - npm i -g npm@6.1.0
  - npm --version

install:
  - npm install

cache:
  npm: true
  node: true

script:
  - npm run jest:ci

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/